name: deploy

on:
  workflow_call:
    inputs:
      release_version:
        type: string
        required: true
      environment:
        type: string
        required: true
      # next_environment:
      #   type: string
      #   required: false
      app_version:
        type: string
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    secrets: inherit
    uses: oleksandrkudin/poc-ndp-workflows/.github/workflows/deploy.yaml@main
    with:
      unit: "poc-ndp-test1"
      release_version: ${{ inputs.release_version }}
      environment: ${{ inputs.environment }}
      #next_environment: ${{ inputs.next_environment }}
